### ISSUE TITLE
Set up dependabot

### ISSUE THREAD

**Issue by Martouta** [Martouta/dev-buddy-openai#3]
Like this in `.github/dependabot.yml` :

```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: ''
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
```
